### PR TITLE
Pull request for WAZO-2078-improve-graphql-internal-requests

### PR DESCRIPTION
**Pull request by fblackburn1**
For the reviewer: I tested Google backend, but not Microsoft

### CODE REVIEW

**Comment by pc-m** [comment]
> For the reviewer: I tested Google backend, but not Microsoft

Thanks, it was very refreshing to revisit external auth... NOT ;)

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
regate

**Comment by fblackburn1** [comment]
regate

**Pull request merged**
