### PR TITLE
Pull request for WAZO-1721-graphql

### PR DESCRIPTION
**Pull request by sduthil**
Add simple GraphQL endpoint returning dummy answers, without authentication.

Depends-On: https://github.com/wazo-platform/wazo-dird-client/pull/10

Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1721

Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1721

### CODE REVIEW

**Comment by sduthil** [comment]
recheck

**Comment by fblackburn1** [comment]
`/{version}/graphql/batch'` endpoint doesn't have documentation nor changelog entry, is it normal?

Should we disable the plugin by default for now? To avoid confusion
Or maybe do not merge this branch for now? To avoid to add confusion in the wazo-platform documentation
Or only add a WIP in the openapi spec?

**Comment by sduthil** [comment]
> Should we disable the plugin by default for now? To avoid confusion
> Or maybe do not merge this branch for now? To avoid confusion in the wazo-platform documentation
> Or only add a WIP label in the openapi spec?

I added a `work_in_progress` label in OpenAPI spec.

**Comment by sduthil** [comment]
recheck

**Pull request merged**
