### PR TITLE
Use Python 3.9, new workers, and Bullseye dependencies

### PR DESCRIPTION
**Pull request by sopelj**

### CODE REVIEW

**Comment by sduthil** [comment]
recheck

**Review by fblackburn1 — DISMISSED** [review]

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Review by fblackburn1 — APPROVED** [review]

**Comment by sopelj** [comment]
recheck (ci still not running)

**Comment by fblackburn1** [comment]
> recheck (ci still not running)

Unfortunately, if the build is "in progress" or badly triggered, the recheck won't trigger anything.
You must push another commit (or amend + force push)

**Comment by sopelj** [comment]
> > recheck (ci still not running)
> 
> Unfortunately, if the build is "in progress" or badly triggered, the recheck won't trigger anything. You must push another commit (or amend + force push)

Oh OK, thanks. It was unclear what state it was in. I thought rechecking would do that.

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
