### PR TITLE
tox: fix syntax

### PR DESCRIPTION
**Pull request by sileht**
Depends-On: https://github.com/wazo-platform/wazo-dird/pull/25

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Comment by pc-m** [comment]
Depends-On: https://github.com/wazo-platform/wazo-dird/pull/25

**Comment by pc-m** [comment]
the wazo-auth mock has no xivo_user_uuid anymore to avoid using a deprecated fields. I added a depend on the PR fixing this issue.

**Comment by sileht** [comment]
recheck

**Pull request merged**
