### PR TITLE
WAZO-3004: `dird` publish to wazo-headers

### PR DESCRIPTION
**Pull request by ja0x**

### CODE REVIEW

**Comment by ja0x** [comment]
recheck

**Comment by ja0x** [comment]
recheck

**Review by fblackburn1 — CHANGES_REQUESTED** [review]
grepping for `routing` leave some of helpers, please remove them if not used

**Comment by ja0x** [comment]
routing_key_fmt must remain on events for the time being, they are still needed for instantiation.  Will be addressed in a later PR

**Review by fblackburn1 — APPROVED** [review]

**Pull request merged**
